# Generated by Django 5.0.6 on 2024-07-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
    ]
